### ISSUE TITLE
how do i get the same layout ?

### ISSUE THREAD

**Issue by raykai** [ppfeufer/eve-online-fitting-manager#32]
Hi,

How can i get the same layout as here:
![help](https://user-images.githubusercontent.com/8138894/32197676-8e08afa4-bd9b-11e7-9f9f-f5cc66109e1f.JPG)

all im getting is this ... 
![how](https://user-images.githubusercontent.com/8138894/32197647-6d47e1e0-bd9b-11e7-9bed-68a8dd01e971.JPG)
what am i missing to show the ship image in the doctrine page?

my inner pages are working tho: 
![1](https://user-images.githubusercontent.com/8138894/32197721-c35afb80-bd9b-11e7-92f0-0360a6be4809.JPG)

**Comment by ppfeufer** [comment]
Untick both checkboxes in Template Settings -> Image Settings.

These first one is the actual article image you can put up for a fitting. The second one is the category image you can set up with the mentioned plugin. If no article image is found, the placeholder (I know, it's ugly) will be displayed.

![screenie_033](https://user-images.githubusercontent.com/2989985/32198282-d07b98a2-bdc7-11e7-93bd-f5040074d911.jpg)

**Comment by raykai** [comment]
sweet ! love your mods :) 
now im only missing a way to show the comment box for the fittings, it would be useful when having it as This fitting is marked as: » Under Discussion. 

i don't mind always having the comment box even if its not set as under Discussion. How would i do this?  

thx for your time :)

**Comment by ppfeufer** [comment]
I don't think I add the ability to comment fittings.

Simple reasons:
- It's a doctrine list, and doctrines are set for a specific purpose. As FC, I am not fond of the idea of random people commenting the doctrine / ships I call for in a fleet. Doctrines should have been discussed with the FC team before making them public. No commenting needed after that.
- It's a fitting set up for discussion, so discuss it with the FC team on your comms. Fittings set for discussion, idea, concept or how ever, should not be part of any official doctrine, so they don't show up in the doctrine lists. Here as well, a comment form is a terribly bad idea, because than everyone and their grand mother would comment that fitting, which is meant to be discussed with the FC team only. Just give them the link and have a nice chat with them all together in your mumble, teamspeak or what ever you use.

In the end, doctrines are meant for pilots to follow, not to comment on them.
