### ISSUE TITLE
Doctrines with 10+ fit are not showed up

### ISSUE THREAD

**Issue by H4Z4RD-H42** [ppfeufer/eve-online-fitting-manager#37]
I finished now adding all the fits of my alliance and I realized that the doctrines with more than 10 fit, show only 10 fit.

![image](https://user-images.githubusercontent.com/6650832/39745863-e3d4efa4-52a8-11e8-8b7b-5e21c85d1611.png)

![image](https://user-images.githubusercontent.com/6650832/39745868-e83de848-52a8-11e8-9cec-74689ec1beac.png)

**Comment by ppfeufer** [comment]
Good catch!

This is probably because of the build in limit of WordPress for articles to show. You can change this in your general WP settings. Let me see if I can find a workaround for that for the plugin.

Workaround you can already implement:
Split the fittings into subcategories of your Capital Ships category. In your case something like Fax, Dreads, Carrier. This also improves the overall overview, since the ship types are not mixed in one group and also gives you direct links to these categories.

**Comment by H4Z4RD-H42** [comment]
I already have this situation. For every ship type, i made a "ship type category and sub-category". Check the screenshot if is like you said.
Changing the number of posts, for example to 50, work fine, but this change also my homepage showing 50 articles. For now i set a static page in homepage, waiting for workaround for the plugin. 

Thank you a lot for your work ;)

![image](https://user-images.githubusercontent.com/6650832/39774940-a7a93c02-52fc-11e8-8314-cf409e816ba4.png)

**Comment by ppfeufer** [comment]
Check the update, this should take care of things.

**Comment by H4Z4RD-H42** [comment]
Oh good, thank you a lot for fix this.
Just one question, i'm new to github... How to update this plugin? Wordpress not ask me to update it... I have to edit the files manually? Or download a full package and upload it with ftp overwriting all files?

Thank you again!

**Comment by H4Z4RD-H42** [comment]
Yesss nice work and thank you a lot ;)
